// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmckrawymowujoixmmtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtY2tyYXd5bW93dWpvaXhtbXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODQ1MTksImV4cCI6MjA3MzM2MDUxOX0.BXWhTZ5WwL6_tQRwj3a4hMBSHt8d0KrDQ26BCA_Nt0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});